### ISSUE TITLE
Identifier 'createRequire' has already been declared

### ISSUE THREAD

**Issue by vldslv-a** [Codex-/knip-reporter#50]
After the 2.4.0 release, I started getting an error.

config: 
```
- name: Post the knip results
        if: github.event_name == 'pull_request'
        uses: codex-/knip-reporter@v2
        with:
          token: ${{ steps.generate-token.outputs.token }}
          verbose: true
```

<img width="702" alt="image" src="https://github.com/user-attachments/assets/956e0d56-9d8d-476a-9b9b-ddd5868358d2">
